# numpy

In [11]:
import numpy as np

## lets do some basic stuff

In [10]:
a = np.array(5)
a

array(5)

In [33]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
a=a.reshape(2,5,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [31]:
print (a.shape)
print (a.ndim)
print (a.size)
print (a.dtype)

(3, 5)
2
15
int32


In [13]:
np.zeros((3,4,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

## some operations

In [42]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [44]:
b

array([0, 1, 2, 3])

In [43]:
a

array([20, 30, 40, 50])

In [50]:
a-b

array([20, 29, 38, 47])

In [55]:
c = a*b

In [56]:
c

array([  0,  30,  80, 150])

In [54]:
c>50

array([False, False,  True,  True])

In [57]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])